### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [stylight/sales-identifier-gtm#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation [url](https://partner.stylight.net) mentioned in the metadata file is behind a login screen. Please provide a valid url.
![Screenshot 2021-10-21 2 35 12 PM](https://user-images.githubusercontent.com/53495700/138360508-bce9333c-0f5a-44e2-a412-f8c86bb6afe2.png)

**Comment by shklqm** [comment]
Hey @praveena-pappu, 
I have changed the documentation url, could you check it again?

**Comment by shklqm** [comment]
Closing in favor of the v2 repo.
